apiVersion: v1
kind: ReplicationController
metadata:
  name: green
  labels:
    app: green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: green
          image: buyifly/udacity-devops-capstone
          ports:
            - containerPort: 80